language: php
php:
  - '5.5'  # Ubuntu Trusty default
  - '5.6'  # MacOS default
  - '7.0'
  - '7.1'

sudo: required

# Only run test when committing to master branch.
branches:
  only:
    - 4.x

env:
  global:
#    - AEGIR_HOSTING_VERSION=7.x-3.x
#    - AEGIR_TESTS_VERSION=master

addons:
  hosts:
    - provision.local.computer

#services:
#  - docker

install:
  - composer install
  - sudo ln -s $PWD/bin/provision /usr/local/bin/provision
  - ls -la

script:

  - provision
  - provision status
  - provision save server_master --context_type=server --remote_host=provision.local.computer --aegir_root=/home/travis --script_user=travis --master_url=provision.local.computer