language: php
php:
  - '5.5'  # Ubuntu Trusty default
  - '5.6'  # MacOS default
  - '7.0'
  - '7.1'

sudo: required

services:
  - docker

# Only run test when committing to master branch.
branches:
  only:
    - 7.x-3.x
    - 4.x

env:
  global:
#    - AEGIR_HOSTING_VERSION=7.x-3.x
#    - AEGIR_TESTS_VERSION=master

addons:
  hosts:
    - provision.local.computer

#services:
#  - docker

before_install:
  - docker run --name provision_db -e MYSQL_ROOT_PASSWORD=root -d -p 3307:3306 mariadb

install:
  - composer install
  - sudo ln -s $PWD/bin/provision /usr/local/bin/provision
  - mkdir /home/travis/config
  - ls -la

script:

  # @TODO: Set non-interactive globally
  - provision -n
  - provision status -n

  # Add server context.
  - provision save server_master -n
    --context_type=server
    --remote_host=provision.local.computer
    --aegir_root=/var/aegir
    --script_user=aegir
    --master_url=provision.local.computer

  # Add services to server_master context.
  - provision services server_master add http -n
    --service_type=apacheDocker
    --http_port=80
    --web_group=www-data
    --restart_command="sudo apache2ctl graceful"

  - provision services server_master add db -n
    --service_type=mysql
    --master_db="mysql://root:root@0.0.0.0:3307"
    --db_grant_all_hosts=0

  - provision services server_master

  # Add platform context
  - provision save platform_hostmaster -n
    --context_type=platform
    --root=/home/travis/hostmaster
    --server_http=server_master
    --makefile=https://raw.githubusercontent.com/aegir-project/provision/4.x/aegir.make
    --make_working_copy=1

  # Add site context
  - provision save hostmaster -n
    --context_type=site
    --platform=platform_hostmaster
    --server_db=server_master
    --uri=provision.local.computer
    --language=en
    --profile=hostmaster
    --db_name=drupal
    --db_user=drupal
    --db_password=drupal

  - provision status -n
  - provision status server_master
  - provision status platform_hostmaster
  - provision status hostmaster


  - provision verify server_master -v

  # Docker creates the host path when docker run happens, in server verify.
  - sudo rm -rf /home/travis/hostmaster

  - provision verify platform_hostmaster -v
  - provision verify hostmaster -v
  
  - provision verify server_master

  - docker ps
  - docker logs servermaster_http_1
  - docker exec servermaster_http_1 sudo apache2ctl -S
